# NM for normalized
{
    'type': "Absolute",

    'NMTOP': 30,
    'NMXHT': 30,
    'NMBOT': 30,

    'NMXWD': 30,
    'NMWID': 90,  # 3* NMXWD

    'BUFLEFT': 6,
    'BUFTOP': 3,
    'BUFBOT': 3,

    'SCALE_BY_TOP_BOTTOM_TOO': True,


## Optional (Re-calcualted in program)
#    'NMHIT': 90,  # NMTOP + NMXHT + NMBOT
#    'TOTWD': 96,  # NMWID + BUFLEFT
#    'TOTHT': 96,  # NMHIT + BUFTOP + BUFBOT
}
